services:
  bot:
    build:
      context: ..
      dockerfile: discord-issue-bot/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/workspace/discord-issue-bot
      - ./data:/data
    environment:
      - DISCORD_BOT_TOKEN
      - GITHUB_TOKEN
    restart: unless-stopped
